set(SOURCES
HttpFsm/HttpAuxiliary.h
HttpFsm/HttpFsmContext.cpp
HttpFsm/HttpFsmContext.h
HttpFsm/HttpFsmStateIFace.h
HttpFsm/HttpFsmStatesCreator.h
HttpFsm/HttpFsmStatesImpl.h
HttpFsm/HttpRequestResponse.h
HttpFsm/StateExecuteDBTransaction.h
HttpFsm/StateFillDBRequest.h
HttpFsm/StateFillHttpResponse.h
HttpFsm/StateParseHttpReq.h
HttpFsm/StateSendHttpResponse.h
PgConnection/PgBackend.cpp
PgConnection/PgBackend.h
PgConnection/PgConnection.cpp
PgConnection/PgConnection.h
PgConnection/PgConnectionTypes.h
PgConnection/PgConnectionWrapper.h
TcpServer/TcpServer.cpp
TcpServer/TcpServer.h
TcpServer/TcpSession.cpp
TcpServer/TcpSession.h
Source.cpp
)