set(SOURCES
../Framework/HttpFsm/HttpAuxiliary.h
../Framework/HttpFsm/HttpFsmContext.cpp
../Framework/HttpFsm/HttpFsmContext.h
../Framework/HttpFsm/HttpFsmStateIFace.h
../Framework/HttpFsm/HttpFsmStatesCreator.h
../Framework/HttpFsm/HttpFsmStatesImpl.h
../Framework/HttpFsm/HttpRequestResponse.h
../Framework/HttpFsm/StateExecuteDBTransaction.h
../Framework/HttpFsm/StateFillDBRequest.h
../Framework/HttpFsm/StateFillHttpResponse.h
../Framework/HttpFsm/StateParseHttpReq.h
../Framework/HttpFsm/StateSendHttpResponse.h
../Framework/PgConnection/PgBackend.cpp
../Framework/PgConnection/PgBackend.h
../Framework/PgConnection/PgConnection.cpp
../Framework/PgConnection/PgConnection.h
../Framework/PgConnection/PgConnectionTypes.h
../Framework/PgConnection/PgConnectionWrapper.h
HttpFsmTests.cpp
)